<?php $this->headTitle()->append('Kontakt') ?>
<section>
    <div class="row">
        <div class="large-6 columns">
            <div class="panel">                
                <section>
                    <h5>Siedziba</h5>
                    <p>00-000 xxxxx, ul. xxxxxxx 0/0</p>
                    <p style="color:white">.</p>
                    <p>
			<iframe width="400" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2400.6759998593866!2d18.585172000000007!3d53.00821349999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47033506dca0a097%3A0xcc0678b9fc5065a3!2sIgnacego+Danielewskiego+7!5e0!3m2!1spl!2spl!4v1402004146610"></iframe><br /><small><a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2400.6757998593866!2d18.585172000000007!3d53.00821349999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47033506dca0a097%3A0xcc0678b9fc5065a3!2sIgnacego+Danielewskiego+7!5e0!3m2!1spl!2spl!4v1402004146610" style="color:#0000FF;text-align:left">Wyświetl większą mapę</a></small>
                    </p>
                </section>
            </div>
        </div>
        <div class="large-6 columns">
            <div class="panel">
                <section>
                    <h5>Stolarnia </h5>
                    <p>00-000, XXXXX ul. XXXXXX 00 </p>
                    <p>(Wjazd od ul.XXXXXXX na terenie XXXXXX)</p>
                    <p>
					<iframe width="400" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f;sspn=0.004167,0.009645&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Kociewska+22,+Toru%C5%84,+kujawsko-pomorskie,+Polska&amp;ll=53.038084,18.636096&amp;spn=0.002258,0.00456&amp;z=17&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=pl&amp;geocode=&amp;q=87-100,+Toru%C5%84+ul.+Kociewska+22+&amp;aq=&amp;sll=53.037833,18.635774&amp;sspn=0.004167,0.009645&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Kociewska+22,+Toru%C5%84,+kujawsko-pomorskie,+Polska&amp;ll=53.038084,18.636096&amp;spn=0.002258,0.00456&amp;z=17&amp;iwloc=A" style="color:#0000FF;text-align:left">Wyświetl większą mapę</a></small>
                    </p>
                </section>
            </div>
        </div>
    </div>
</section>





