<?php $this->headTitle()->append('Aukcje') ?>
<section>
    <div class="row">
        <div class="large-8 columns">
            <div class="panel">
                <h5>Aukcje</h5>                
                <section>
                    <h6>Zapraszamy na aukcje na platformie allegro. </h6>
                    <p><a target="_blank" href="http://allegro.pl/listing/user/ ">http://allegro.pl/listing/user/ </a></p>
                <p><a target="_blank" href="http://allegro.pl/listing/user/">http://allegro.pl/listing/user/</a></p>
		    </section>
            </div>
        </div>
        <div class="large-4 columns">
            <div class="panel">
                <!--
		<h5>Dodatkowe informacje</h5>
                <section>
                    <h6>O aukcjach:</h6>
                    <p>Opis dodatkowych informacji</p>
                </section>	
		-->

            </div>
        </div>
    </div>
</section>
