<?php $this->headTitle()->append('Firma') ?>
<section>
    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                <h4>tttt ttttt  xx.xxx. xxxxxxx</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="large-4 columns">
            <div class="panel">
                <section>
                    <h6>Wykonujemy konstrukcje drewniane:</h6> 
                    <ul>
                        <li>domki letniskowe</li>
                        <li>altany</li>
                        <li>drewutnie</li>
                        <li>tarasy</li>
                        <li>zadaszenia schodów i tarasów</li>
                        <li>wiaty samochodowe</li>
                    </ul>
                </section>
            </div>
        </div>
        <div class="large-8 columns">
            <div class="panel">
                <section>
                    <h6>
                        Nasze konstrukcje podlegają wszelkim modyfikacjom według wskazań klienta:
                    </h6>
                    <p>
                        mogą być większe lub mniejsze, można dodać okno lub przestawić je na inną ścianę.
                    </p>
                    <p>
                        Konstrukcje dostosowujemy do Państwa potrzeb. W cenie otrzymują
                        Państwo materiał przygotowany na wybraną konstrukcję, jej montaż
                        oraz dojazd do klienta na terenie całego kraju. Oferujemy różne
                        systemy płatności. Jeśli mają Państwo jakiekolwiek pytania prosimy
                        o <a href="/index/about">kontakt</a>. Zapraszamy do współpracy!
                    </p>
                </section>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                <h6>
                    Posiadamy bardzo bogatą ofertę dla właścicieli rodzinnych ogórdków działkowych.
                </h6>
            </div>
        </div>
    </div>

</section>
