<?php $this->headTitle()->append('Strona glowna') ?>
    <section>
        <div class="row home">
            <div class="small-12 large-4 columns">
                  <div class="panel" id="experience">
                    <h5>Doświadczenie</h5>
                        <p>
        Jesteśmy firmą z ugruntowaną pozycją na rynku. Decydujemy się spełniać indywidualne życzenia klientów i odważnie realizujemy nowe i nietypowe projekty. W galerii znajdą Państwo przygotowane przez Nas konstrukcje. Zapraszamy do zapaznania się z nimi.
                        </p>
                </div>
            </div>
            <div class="small-12 large-4 columns">
                <div class="panel" id="technology">
                    <h5>Nasza technologia</h5>
                        <p>
                        <b>Konstrukcja:</b>

drewno suche, 12% wilgotności, świer syberyjski oraz sosna;
na indywidualne zamówienia różne rodzaje drewna egzotycznego,
<a href="/index/technology">więcej o naszej technologii..</a>
</p>

                        </p>
                </div>
            </div>                
            <!-- <div class="small-12 large-4 columns">
                <div class="panel" id="installment">
                   <h5>Wygodne raty</h5>
                        <p> Umożliwiamy Państwu skorzystanie z przyjaznego systemu ratalnego GETIN BANKU.</p>
                </div>
            </div> -->
        </div>          
    </section>