<?php $this->headTitle()->append('Kontakt') ?>
<section>
    <div class="row">
        <div class="large-12 columns">
            <div class="panel"> 
                <h5> Umożliwiamy Państwu skorzystanie z przyjaznego systemu ratalnego GETIN BANKU.</h5>
                <section>
                    <h6>
                        Zalety kredytu:
                    </h6>
                    <ul>
                        <li>Niskie oprocentowanie.</li>
                        <li>Możliwość uzyskania kredytu bez dodatkowych ubezpieczeń i zabezpieczeń.</li>
                        <li>Raty udzielne są na okres maxymalnie 5 lat, dając Państwu elastyczność przy określaniu wysokości raty.</li>
                        <li>Szybka weryfikacja kredytobiorcy.</li>
                        <li>Decyzja kredytowa w przeciągu kilku minut.</li>
                        <li>Wypłata kredytu odbywa się bezpośrednio na konto Naszej firmy PO zamontowaniu wybranego przez Państwa produktu.</li>
                    </ul>
                </section>                
            </div>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                <h6>Chętnych zapraszamy do <a href="/index/about">kontaktu.</a> Tel: 513496288.</h6>
            </div>            
        </div>
    </div>      
</section>
