<?php $this->headTitle()->append('Technologia') ?>
<section>
    <div class="row">
        <div class="large-8 columns">
            <div class="panel"> 
                <h5>Nasza Technologia</h5>
                <section>
                    <h6>Konstrukcja:</h6>
                    <p>drewno suche, 12% wilgotności, świer syberyjski oraz sosna,
                        na indywidualne zamówienia różne rodzaje drewna egzotycznego
                    </p>
                </section> 
                <section>
                    <h6>Elewacja:</h6>
                    <p>deska pióro-wpust; grubość 18,5x28mm;</p>
                </section>    
                <section>
                    <h6>Pokrycie dachu:</h6>
                    <ul>
                        <li>domki - gont bitumiczny, cztery kolory: czerwień, brąz, zieleń oraz szary</li>
                        <li>drewutnie - gont bitumiczny lub ondulina</li>
                        <li>drewutnie - gont bitumiczny lub ondulina</li>
                        <li>wiaty garażowe - ondulina, blachodachówka lub gont;</li>
                    </ul>                    
                </section>    
            </div>
        </div>      
        <div class="large-4 columns">
            <div class="panel">
                <h5>Dodatkowe informacje</h5>	
                <section>
                    <h6>Zabezpieczenie drewna:</h6>
                    <p>impregnaty firmy "drewnochron" - 5 lat ochrony, gwarancja producenta;</p>
                </section>
                <section>
                    <h6>kolory impregnatów:</h6>
                    <ul>
                        <li>bezbarwny</li>
                        <li>cedrowy</li>
                        <li>dąb</li>
                        <li>mahoń</li>
                        <li>ciemny orzech</li>
                        <li>palisander</li>
                        <li>palisander średni</li>
                        <li>sosna</li>
                        <li>tik</li>
                        <li>zielony</li>
                    </ul>
                    <h6>
                    	<img src="/img/drewnochron-extra-paleta.png" />
                    </h6>
                </section>
            </div>
        </div>            
    </div>
    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                <h6>Na indywidualne życzenie klienta kładziemy dachówkę.</h6>
            </div>            
        </div>
    </div>             
</section>