<?php $categoryId = $this->getHelper('Navigation')->view->categoryId; ?>
<section>
    <div id="nav" class="row">
        <div class="large-12 columns">
            <div class="panel">
                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <a href="<?= $this->url(array('page' => $this->previous,'category_id'=>$categoryId)); ?>">&lt; Poprzedni</a> |
                <?php else: ?>
                    <span class="disabled">&lt; Poprzedni</span> |
                <?php endif; ?>

                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <a href="<?= $this->url(array('page' => $page,'category_id'=>$categoryId)); ?>"><?= $page; ?></a>
                    <?php else: ?>
                        <?= $page; ?>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    | <a href="<?= $this->url(array('page' => $this->next,'category_id'=>$categoryId)); ?>">Następny &gt;</a> 
                <?php else: ?>
                    | <span class="disabled">Następny &gt;</span> 
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
