<?php $this->headTitle()->append('Zmiana hasła Administratora') ?>

<?= $this->render('imageCategoryMenu.phtml') ?>

<section>
    <div class="row">
        <div class="large-4 columns">
            <div class="panel">
            </div>
        </div>
        <div class="large-4 columns">
            <div class="panel">
                <h5>Zmiana hasła administratora</h5>

                <table>
                    <?php if (isset($this->passwordsAreEqual) && !$this->passwordsAreEqual): ?>
                        <p>Błąd: Wpisane hasła są różne</p>
                    <?php endif; ?>

                    <form action="/user/changeAdminPassword">
                        <tr>
                            <td>Hasło</td>
                            <td><input type="password" name="adminPassword" value="<?php echo $this->adminPassword; ?>" /></td>
                        </tr>
                        <tr>
                            <td>Powtórz hasło</td>
                            <td><input type="password" name="confirmationAdminPassword" value="<?php echo $this->confirmationAdminPassword; ?>" />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><input type="submit" name="Zmień" value="Zmień" /></td>
                        </tr>
                    </form>
                </table>
            </div>
        </div>
        <div class="large-4 columns">
            <div class="panel">
            </div>
        </div>
</section>

